# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html
# ApplicationYmlConfig #
web:
  version: "JRE 17"

# server #
server:
  port: 8027

# netty #
spring:
  main:
    web-application-type: reactive
  webflux:
    base-path: /java-reactive-microservice-mongodb
  data:
    mongodb:
      host: localhost
      database: local
      port: 27017
      authentication-database: admin
      username: local
      password: local

# logger #
logging:
  level:
    org:
      springframework:
        data: WARN
        web: WARN
    net:
      marco27:
        api: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/java-reactive-microservice-mongodb.log
# Actuator endpoints: https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints
management:
  endpoints:
    web:
      exposure:
        include:
          - beans
          - env
          - health
          - logfile
          - loggers
          - metrics
          - threaddump
  endpoint:
    beans:
      enabled: true
    env:
      enabled: true
    health:
      show-details: always
    logfile:
      enabled: true
    loggers:
      enabled: true
    metrics:
      enabled: true
    threaddump:
      enabled: true
